sudo: required
language: java
jdk: oraclejdk8
addons:
  ssh_known_hosts:
  - 47.93.9.236:22008
  sonarcloud:
    organization: tron-key
    token:
      secure: "GpJmwo5kPZV0MtPLN56xbKUFPBFC5j53ie1aK79Zg4OkinuwOCiAPdzsn4J6c60j+Ms5eKK+0BrEqW62ZD0vFHrBIw30XcUpzD0Mcjpwaxerz3bmUq1RoA0CIO64qKqEVjsWNDkduHKs2Tw8bAMXT9TX3BcBzIGiigOjC0ceRFYt1l6CcAi0eDZQll6GHw0zadWKJd9qiaJEpGIbcY04nRcKzZUvkUlMIIhYF5LCP79jdIo+DHAGEIU74qBhEqniS5hW9gXwv+Imm0ivhlMqX+Eoq4dEqmTlFFsTPEzJZTa3P0g/5CRYSc9txhzrgqoB/jXwgAEBt+n0uCLU1CrlNstzC8dL/JaqTBFaG7J2tkdCL58FncUgkDUiXLzt7kicADipvKL22sKWDUylzE1dRHuiXcRfTjcbAautm8EXLaywYamBCW8CAHCgpJ0dO0wbyAK1XSz34+TCrbb+Kdk9zfbWidDVYY4OlrTY1CJvf38ROHfAq+zKdU3kO713o88mQPZHUmnSUC7ObNl1WwCN6lD62E3QW2ZxUxcLEmGShE6v2e/x5shrD6tDEQjuvGGvV2v15b8Bhfpl5wcxoLQnTyW5ID1Ckq6xv4N8rLGueNnL+niBQKqAEtrLTyi+E3avaRmVRWWxFH8WqRjaFdYZ7Qar9VWjyEmZpPMMBQv7lCc="
cache:
  directories:
    - '$HOME/.sonar/cache'
script:
- sonar-scanner
skip_build:
- README.md：
- LICENSE
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
after_deploy:
- "./gradlew stest"

